replicaCount: 2

image:
  repository: a2barros78/node-shop
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

postgres:
  image: postgres:16
  volumeSize: 10Gi
  host: postgres
  database: evershop
  user: postgres
  password: postgres

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

