replicaCount: 2

image:
  repository: <docker_username>/evershop
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

postgres:
  image: postgres:15-alpine
  volumeSize: 10Gi
  database: evershopdb
  user: evershopuser
  password: evershopPassword123

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
