apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-shop
  namespace: argocd
  # annotations:
  #   argocd-image-updater.argoproj.io/write-back-method: git
  #   argocd-image-updater.argoproj.io/image-list: node-shop=a2barros/node-shop
  #   argocd-image-updater.argoproj.io/evershop.update-strategy: latest
spec:
  project: tpdevops
  source:
    repoURL: 'git@github.com:devopswave/argo-node-shop.git'
    targetRevision: test002
    path: charts/node-shop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shop-node
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
