apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-shop
  namespace: shop-node
  labels:
    app: node-shop
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-shop
  template:
    metadata:
      labels:
        app: node-shop
    spec:
      containers:
      - name: node-shop
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "{{ .Values.postgres.user }}"
        - name: DB_PASSWORD
          value: "{{ .Values.postgres.password }}"
        - name: DATABASE_NAME
          value: "{{ .Values.postgres.database }}"
