apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: shop-node
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: {{ .Values.postgres.image }}
        name: postgres
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.postgres.database }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgres.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgres.password }}"
        ports:
        - containerPort: 5432
          name: postgres
