apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-shop
  namespace: shop-node
  labels:
    app: node-shop
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-shop
  template:
    metadata:
      labels:
        app: node-shop
    spec:
      containers:
      - name: node-shop
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DATABASE_NAME
          value: "{{ .Values.postgres.database }}"
