apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: shop-node
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: create-pgdata-dir
        image: alpine
        command: ["mkdir", "-p", "/var/lib/postgresql/data/pgdata"]
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - image: {{ .Values.postgres.image }}
        name: postgres
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.postgres.database }}"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
