apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: shop-node
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres"
