apiVersion: v1
kind: Service
metadata:
  name: node-shop
  namespace: shop-node
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    app: node-shop
